# Generated by Django 3.0.6 on 2020-07-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='skills',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='cv',
            name='summary',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='address',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='email',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='cv',
            name='mobile',
            field=models.CharField(default='None', max_length=15),
        ),
        migrations.AlterField(
            model_name='cv',
            name='name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='cv',
            name='telephone',
            field=models.CharField(default='None', max_length=15),
        ),
    ]
